[package]
name = "runtime-tokio"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
workflow-core = { path = "../workflow-core" }
harness-core = { path = "../harness-core" }
harness = { path = "../harness" }
protocol = { path = "../protocol" }
tokio = { version = "1", default-features = false }
